### PR TITLE
add post-downscaling wet day correction in the workflows

### PR DESCRIPTION
**Pull request by emileten**
@brews I went ahead and added changes to make use of the option developed here https://github.com/ClimateImpactLab/dodola/pull/141. From the `biascorrectdownscale` template, I passed over the already existing `correct-wetday-frequency` parameter onto the `qplad` template, then within it to `with-lat-chunks` and within it to `apply-qplad`. At that point the value of the parameter is passed to the `boolean` `click` option `--wet-day-post-correction`. How does this sound to you ? I was thinking about testing that in an actual `e2e-pr` workflow run, but I wanted your input first. 

Also -- I think that's for @dgergel -- note this means there isn't an option to apply this correction only pre or only post downscaling, it arbitrarily does both. Is that ok ?

### CODE REVIEW

**Review by dgergel — APPROVED** [review]
@emileten it's fine if the pipeline only does both, as there isn't a situation in which we'd want to do either/or. We do want it only for precip, but I don't think you changed that so that's okay. 

@brews would be great if you reviewed this too before we merge.

**Comment by brews** [comment]
Nice! @emileten This is going to need a few changes. I'm going to move this into a "draft" PR, until we walk through how to test and run the dev releases of `dodola`, @emileten, then we can review this.

**Comment by emileten** [comment]
@brews is this needed to run a "correct" `e2e` precip workflow?

**Comment by emileten** [comment]
@brews I think I fixed one problem with this, not sure it was all or even part of what you were worried about.

Back then I added the `correct-wetday-frequency` option to `qplad.qplad`. But _not_ to `qplad.main` which under the hood calls `qplad.qplad`. Without a default value anywhere, a `qplad` workflow running through its entrypoint would have crashed. 

So, the few commits above I think should fix this.

**Review by brews — APPROVED** [review]
Appreciate this contribution, @emileten ! I think this is good to go. 👍

**Comment by brews** [comment]
I'm going to merge this and begin testing now that we've got some precipitation data to play with from https://github.com/ClimateImpactLab/downscaleCMIP6/pull/485.

**Pull request merged**
