### PR TITLE
Migrate clean, download workflows to new Azure storage containers

### LINKED ISSUE #152: Migrate storage account containers to specialized expanded containers
With PR #151 we added several containers for Azure blob storage to accommodate an expanded workflow. The current workflows should be updated to use these new containers before the old containers can be mothballed.

Biascorrected and downscaled output be directed to:

- `biascorrected`
- `downscaled`

Paths in the `workflows/intake-catalog.yaml` should also be updated.

### PR DESCRIPTION
**Pull request by brews**
Close #152

### CODE REVIEW

**Review by dgergel — APPROVED** [review]
@brews this looks good to me, feel free to merge when you're ready.

**Comment by brews** [comment]
I'm going to switch this PR to a draft because we might shift things to work with outside collaborators interested in the raw data.

**Comment by dgergel** [comment]
Smart. Sounds good to me.

**Comment by brews** [comment]
We might need to make more radical changes to how we store raw data but for now I'm going to keep this PR focused just on moving to the new `raw-cmip6`, `raw-era5`, `clean-cmip6`, `clean-era5` storage containers.

Merging.

**Pull request merged**
