### PR TITLE
workflowtemplate to regrid cleaned cmip6 data

### PR DESCRIPTION
**Pull request by emileten**
- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] docs reflect changes
 - [ ] passes ``flake8 downscale tests docs``
 - [ ] entry in HISTORY.rst

This addresses a request to have access to the clean GCM CMIP6 data regridded from the native GCM grid to a common 1 degree resolution grid, without any of the data alteration that happens in the full pipeline, e.g. wetday correction. We need this for tasmax, tasmin, precip and for all models and all scenarios. 

I kept only what we need from the `biascorrectdownscale`, `qdm` and `qdm-preprocess` templates and collected all that in a single workflow template that does the following : 

- takes `job` and a `regrid-method` parameters
- from the former builds the`in-zarr` path of the clean data -- that should exist already -- and an `out-zarr` path for the regridded data, that I stored in our `support..` bucket in a `regrid-cmip6` new folder. The rest of the paths follow the usual structure.
- next it does the `add-cyclic` operation if needed, then a first rechunk to gather spatial chunks, then the regrid, and then again a rechunking to split the data across space, and saves that to the final location. 

I removed the 'dtr threshold' and 'wetday correction' parts as we don't want any of that here. 

@brews let me know what you think ! 

Everything ran successfully.

### CODE REVIEW

**Review by brews — APPROVED** [review]
Thanks for this @emileten!

I think this is spot on.

I have one required change and then minor suggestions that are up to you.

### REQUIRED

- If you're going to do this as a WorkflowTemplate here instead of a Workflow in `workflows/regrid-cmip6.yaml` then you need to add this file to `workflows/templates/kustomization.yaml` otherwise it will not deploy to the cluster.

### Optional

I think you can knock off some lines and simplify things by removing the middle `preprocess` template. For example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: regrid-cmip6
  annotations:
    workflows.argoproj.io/description: >-
      Regrid already existing and cleaned CMIP6 data to a common 1 degree resolution grid
    workflows.argoproj.io/tags: cmip6,dc6,regrid
    workflows.argoproj.io/version: '>= 3.1.0'
  labels:
    component: regrid-cmip6
spec:
  entrypoint: with-jobs
  arguments:
    parameters:
      - name: jobs
        value: |
          [
            {
              "target": "ssp",
              "variable_id": "tasmax",
              "historical": { "activity_id": "CMIP", "experiment_id": "historical", "table_id": "day", "variable_id": "tasmax", "source_id": "ACCESS-CM2", "institution_id": "CSIRO-ARCCSS", "member_id": "r1i1p1f1", "grid_label": "gn", "version": "20191108" },
              "ssp": { "activity_id": "ScenarioMIP", "experiment_id": "ssp245", "table_id": "day", "variable_id": "tasmax", "source_id": "ACCESS-CM2", "institution_id": "CSIRO-ARCCSS", "member_id": "r1i1p1f1", "grid_label": "gn", "version": "20191108" }
            }
          ]
      - name: regrid-method
  templates:


      # Loop through each job listed.
    - name: with-jobs
      inputs:
        parameters:
          - name: jobs
          - name: regrid-method
      steps:
        - - name: variable-id-switch
            template: variable-id-switch
            arguments:
              parameters:
                - name: job
                  value: "{{ item }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
            withParam: "{{ inputs.parameters.jobs }}"

    - name: variable-id-switch
      inputs:
        parameters:
          - name: job
          - name: regrid-method
          - name: variable-id
            value: "{{=jsonpath(inputs.parameters.job, '$.variable_id') }}"
      steps:
        - - name: parameterize-simple-job
            template: parameterize
            arguments:
              parameters:
                - name: target
                  value: "{{=jsonpath(inputs.parameters.job, '$.target')}}"
                - name: historical
                  value: "{{=toJson(jsonpath(inputs.parameters.job, '$.historical'))}}"
                - name: ssp
                  value: "{{=toJson(jsonpath(inputs.parameters.job, '$.ssp'))}}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"

      # Start work for target simulation, with target-specific configs.
    - name: parameterize
      inputs:
        parameters:
          - name: target
          - name: ssp
          - name: historical
          - name: regrid-method
          - name: domainfile1x1
            value: "gs://support-c23ff1a3/domain.1x1.zarr"
      steps:
        - - name: historical
            template: regrid-cmip6
            arguments:
              parameters:
                - name: simulation
                  value: "{{ inputs.parameters.historical }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
            when: "{{inputs.parameters.target}} == historical"
          - name: ssp
            template: regrid-cmip6
            arguments:
              parameters:
                - name: simulation
                  value: "{{ inputs.parameters.ssp }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domainfile1x1
                  value: "{{ inputs.parameters.domainfile1x1 }}"
            when: "{{inputs.parameters.target}} == ssp"


    - name: regrid-cmip6
      inputs:
        parameters:
          - name: simulation
          - name: regrid-method
          - name: domainfile1x1
      dag:
        tasks:
          - name: get-input-clean-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.experiment_id')}}"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.grid_label')}}"
                - name: version
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.version')}}"
                - name: base-url
                  value: "gs://clean-b1dbca25/cmip6"
          - name: get-output-regridded-url
            templateRef:
              name: catalog
              template: get-fsspec-url-from-parameters
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.experiment_id')}}"
                - name: activity-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.activity_id')}}"
                - name: table-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.table_id')}}"
                - name: variable-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.variable_id')}}"
                - name: source-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.source_id')}}"
                - name: institution-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.institution_id')}}"
                - name: member-id
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.member_id')}}"
                - name: grid-label
                  value: "{{=jsonpath(inputs.parameters.simulation, '$.grid_label')}}"
                - name: version
                  value: "{{workflow.creationTimestamp.Y}}{{workflow.creationTimestamp.m}}{{workflow.creationTimestamp.d}}{{workflow.creationTimestamp.H}}{{workflow.creationTimestamp.M}}{{workflow.creationTimestamp.S}}"
                - name: base-url
                  value: "gs://support-c23ff1a3/regrid-cmip6"
          - name: check-to-add-cyclic-pixels
            depends: get-input-clean-url
            template: check-to-add-cyclic-pixels
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.get-input-clean-url.outputs.parameters.out-url }}"
                - name: add-cyclic
                  value: "{{=inputs.parameters['regrid-method'] == 'bilinear' ? 'lon' : 'false'}}"
          - name: move-chunks-to-time
            depends: check-to-add-cyclic-pixels
            templateRef:
              name: rechunk
              template: rechunk
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.check-to-add-cyclic-pixels.outputs.parameters.out-zarr }}"
                - name: time-chunk
                  value: "365"
                - name: lat-chunk
                  value: -1
                - name: lon-chunk
                  value: -1
          - name: regrid
            depends: move-chunks-to-time
            templateRef:
              name: regrid
              template: regrid
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.move-chunks-to-time.outputs.parameters.out-zarr }}"
                - name: regrid-method
                  value: "{{ inputs.parameters.regrid-method }}"
                - name: domain-file
                  value: "{{ inputs.parameters.domain-file }}"
          - name: move-chunks-to-space
            depends: regrid
            templateRef:
              name: rechunk
              template: rechunk
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.regrid.outputs.parameters.out-zarr }}"
                - name: out-zarr
                  value: "{{ inputs.parameters.out-zarr }}"
                - name: time-chunk
                  value: -1
                - name: lat-chunk
                  value: 10
                - name: lon-chunk
                  value: 10


    - name: check-to-add-cyclic-pixels
      inputs:
        parameters:
          - name: in-zarr
          - name: add-cyclic
            value: "false"
      dag:
        tasks:
          - name: add-cyclic
            template: add-cyclic
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ inputs.parameters.in-zarr }}"
                - name: add-cyclic
                  value: "{{ inputs.parameters.add-cyclic }}"
            when: "{{inputs.parameters.add-cyclic}} != false"
      outputs:
        parameters:
          - name: out-zarr
            valueFrom:
              expression: "inputs.parameters['add-cyclic'] != 'false' ? tasks['add-cyclic'].outputs.parameters['out-zarr'] : inputs.parameters['in-zarr']"


      # Prevents weird artifacts in datasets near international dateline with
      # bilinear regridding.
    - name: add-cyclic
      inputs:
        parameters:
          - name: in-zarr
          - name: out-zarr
            value: "gs://scratch-170cd6ec/{{ workflow.uid }}/{{ pod.name }}/cyclic-added.zarr"
          - name: add-cyclic
            value: "lon"
      outputs:
        parameters:
          - name: out-zarr
            value: "{{ inputs.parameters.out-zarr }}"
      script:
        image: us-central1-docker.pkg.dev/downscalecmip6/private/dodola:0.12.0
        command: [ python ]
        source: |
          import logging
          import dodola.repository as storage
          from dodola.core import _add_cyclic

          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger(__name__)

          logger.info("Adding cyclic wraparound pixels")
          storage.write(
              "{{ inputs.parameters.out-zarr }}",
              _add_cyclic(
                  storage.read("{{ inputs.parameters.in-zarr }}"),
                  dim="{{ inputs.parameters.add-cyclic }}".lower()
              )
          )
        resources:
          requests:
            memory: 16Gi
            cpu: "1000m"
          limits:
            memory: 18Gi
            cpu: "2000m"
      activeDeadlineSeconds: 1200
      retryStrategy:
        limit: 4
        retryPolicy: "Always"
        backoff:
          duration: 30s
          factor: 2

```

You could also remove all that `check-to-add-cyclic-pixels` by referencing it in `qdm-preprocess` and then remove the unused last ~100 lines of the `workflowTemplate` (the `add-cyclic` and `check-to-add-cyclic-pixels` templates). E.g.:
```yaml
          - name: check-to-add-cyclic-pixels
            depends: get-input-clean-url
            templateRef:
              name: qdm-preprocess
              template: check-to-add-cyclic-pixels
            arguments:
              parameters:
                - name: in-zarr
                  value: "{{ tasks.get-input-clean-url.outputs.parameters.out-url }}"
                - name: add-cyclic
                  value: "{{=inputs.parameters['regrid-method'] == 'bilinear' ? 'lon' : 'false'}}"
```

This is all optional!

**Comment by emileten** [comment]
Thanks a lot @brews for these suggestions ! 

About the 'required' : in fact I ran this is a `Workflow`, not a `WorkflowTemplate`. Since I don't think this is meant to be re-used by other workflows, I am thinking of switching back to the former type. Are you okay with it ?

**Comment by brews** [comment]
> Thanks a lot @brews for these suggestions !
> 
> About the 'required' : in fact I ran this is a `Workflow`, not a `WorkflowTemplate`. Since I don't think this is meant to be re-used by other workflows, I am thinking of switching back to the former type. Are you okay with it ?

@emileten, Yeah, I think that's fine — we can always move it to a `workflowTemplate` later if needed or whatever.

If you want to keep it as a `Workflow`, then I'd move the manifest from `workflows/templates/regrid-cmip6.yaml` to `workflows/regrid-cmip6.yaml` so it's not mixed in with the other hard templates.

**Comment by emileten** [comment]
Great I am going to do that since it's probably not something we'll reuse a lot. Along with some cleanup you suggested. 

I will probably add another short workflow YAML like that for some ERA data that's based on what we already have... In which case I might pin you again for a very quick re-review if you don't mind.

**Comment by brews** [comment]
@emileten Yeah, sure. Sounds good to me. I'm happy to re-review whenever you're ready.

**Comment by emileten** [comment]
Thank you again for the review.

**Review by brews — APPROVED** [review]
LGTM! A thoughtful and helpful contribution. Thank you.

**Comment by brews** [comment]
@emileten I think this is ready to merge whenever you're ready.

For the record, did you have (test) workflow runs for these that you can link to?

**Comment by emileten** [comment]
@brews ah I didn't. I will do this real quick and if it checks out I will just merge. Thanks !

**Comment by emileten** [comment]
Checks out ! `regrid-cmip6` https://argo.cildc6.org/workflows/default/regrid-cmip6-dev-7cppv?tab=workflow. `regrid-era5` : https://argo.cildc6.org/workflows/default/regrid-era5-4jjcv?tab=workflow.

**Pull request merged**
