### PR TITLE
Increase valid tasmin, tasmax range max to allow hot UKESM1-0, HadGEM3

### LINKED ISSUE #558: HadGEM3-GC31-LL tasmax ssp585 min value out of range
Workflow : https://argo.cildc6.org/archived-workflows/default/e46de2d6-5612-4dbf-92a6-c06060dc3b42

Log : 
```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MOHC/HadGEM3-GC31-LL/ssp585/r1i1p1f3/day/tasmax/gn/v20200114.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 32, in clear_memory_intensive_tests
    _test_temp_range(d, v)
  File "/opt/dodola/dodola/core.py", line 760, in _test_temp_range
    assert (ds[var].min() > 130) and (
AssertionError: tasmax values are invalid

```

### LINKED ISSUE #559: UKESM1-0-LL tasmax all cleaned ssp values out of range
Workflow : https://argo.cildc6.org/archived-workflows/default/269fc29e-fe52-4039-a33e-6774bd720415

Log example :  
```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MOHC/UKESM1-0-LL/ssp585/r1i1p1f2/day/tasmax/gn/v20190726.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 32, in clear_memory_intensive_tests
    _test_temp_range(d, v)
  File "/opt/dodola/dodola/core.py", line 760, in _test_temp_range
    assert (ds[var].min() > 130) and (
AssertionError: tasmax values are invalid
```

### PR DESCRIPTION
**Pull request by brews**
Note, this increases max allowed tasmin, tasmax to 377 K. See the issues above for details.

close #558
close #559

### CODE REVIEW

**Review by emileten — APPROVED** [review]
Thanks @brews !

**Comment by emileten** [comment]
I will go ahead and make a PR updating the dodola version where needed to account for https://github.com/ClimateImpactLab/dodola/pull/179 ? If you're not already on it @brews.

**Comment by brews** [comment]
@emileten I don't have a PR for that fix. That's all yours.

**Comment by brews** [comment]
A [test run](https://argo.cildc6.org/archived-workflows/default/4e289986-9470-4ea2-96c9-aef788895183) on UKESM1.0 data from the above issue confirms this PR runs and resolved the problem.

Merging.

**Pull request merged**
