### PR TITLE
Update dodola in standardize-cmip6

### LINKED ISSUE #574: large EC-Earth data fails at CMIP6 cleaning due to OOM error
Blocks progress on #263 and #266.

Workflow : https://argo.cildc6.org/archived-workflows/default/28a83ec8-998f-4d61-96f1-73f57387d3e7

One can look at the `standardize_gcm` step, in cleaning : each and every retry failed due to OOM errors.

I picked one of these failed pods input and reproduced the OOM on JupyterHub with a 48GB server, which is the specified resource limit in this pod in our argo workflow.

In `standardize_gcm` we load the data in memory. `EC-Earth3` pr is 256 * 512 * time, so higher resolution than other models, but that's still only ~16GBs for the future data. The problem is that we have operations in `standardize_gcm` that make the memory usage kind of blow up, I think. 

Another model of this family, with a lower resolution, that is running here `https://argo.cildc6.org/workflows/default/e2e-ec-earth3-veg-lr-pr-t8stn?tab=workflow&nodeId=e2e-ec-earth3-veg-lr-pr-t8stn-1904431442`, nearly crashed at the same steps for the same reason, but survived thanks to retries.

### PR DESCRIPTION
**Pull request by emileten**
This makes use in the `clean-cmip6` workflow of a recent change in `dodola.services.clean_cmip6` and `dodola.core.standardize_gcm`, released in `dodola:0.17.0`. 

This lets in models with large, high resolution data. Closes #574.

### CODE REVIEW

**Review by brews — APPROVED** [review]
LGTM!

**Comment by emileten** [comment]
Quick question @brews. I label PRs with 'bug' whenever a given PR closes an issue that was opened due to a failed workflow. 

I am wondering what's your rule of thumb on PR labelling (aka, when you use 'enhancement', or when you use 'bug').

It's kind of minor but I am usually unsure on labels, so I was wondering what's your approach.

**Comment by brews** [comment]
@emileten Yeah, that's a good question. "enhancement" is like it adds new behavior or a new feature while "bug" is something was going wrong or faulty -- loosely.

With the UKESM/HadGEM3 PR I just did, the code in dodola and our workflows was functioning and behaving as designed — the change in the PR is because we wanted something _new_ to accommodate the hot model runs — thus I label it as an enhancement.

**Comment by brews** [comment]
In the case of this PR, I'd say it's a bug, and specifically a regression. It used to work correctly but no longer does due to a recent change.

**Pull request merged**
