### PR TITLE
Add DTR parameter files based on tasmin, tasmax

### PR DESCRIPTION
**Pull request by brews**
If it's not here, then the required inputs likely didn't exist.

The JSON is all compacted down to a single line with whitespace removed to reduce file size because these get a bit big when all ssps and historical are in the same file. Sorry. Its far less human-readble. We can experiment with this. If you need help formating it so its easy to read you can use [an online pretty printing tool](https://jsonformatter.org/json-pretty-print).

For future reference: Code I did this with is [here](https://gist.github.com/brews/e8b0aeccf37ada2dd3424887635c0aa4). You only need about half of it. It's super rough. Lots of extra bits for testing and validation.

### CODE REVIEW

**Comment by brews** [comment]
@dgergel, tagging you for review as a heads up that this is what we have for first pass at DTR.

**Comment by brews** [comment]
Emile, you can check this out to know how the sausage is made, but a heavy review is def not required.

**Comment by dgergel** [comment]
@brews do you want a closer review here or just high level? Looks like you tested that all of the data is there in the gist you posted

**Comment by brews** [comment]
@dgergel This doesn't need a close review. I tagged you as a heads up because this was heavy. I think we got the obvious/glaring parameter bugs with that early checking but we will see.

**Pull request merged**
