### PR TITLE
Remove unused parameter files for tasmin

### PR DESCRIPTION
**Pull request by brews**
This removes all the workflow parameter files for tasmin runs. 

We no longer need this information because any used tasmin information is part of the "dtr" parameter files. "tasmin" itself is not run through the workflow as a variable.

### CODE REVIEW

**Comment by brews** [comment]
Tagging @dgergel  and @delgadom for review on this change, though this is a low priority.

**Comment by delgadom** [comment]
Fine with me!

**Comment by dgergel** [comment]
@brews my concern with this is that the tasmin parameter file info may be useful to have around in a human readable format. Although all of this information _is_ in the DTR parameter files, it's harder to read/find if you are looking for some info for documentation, and think we will be in a few months once we are getting ready for our public release and tying up our paper. I'd actually suggest keeping these around for the time being.

**Comment by brews** [comment]
@dgergel Would you be amiable to this change if the DTR parameter files were pretty printed? 

I can show you what that would look like.

**Comment by dgergel** [comment]
possibly/probably can you give me an example of what you mean specifically?

**Comment by brews** [comment]
@dgergel Here is an example of pretty-printed DTR parameters: [ACCESS-ESM1-5-dtr-TEST.yaml.zip](https://github.com/ClimateImpactLab/downscaleCMIP6/files/7810770/ACCESS-ESM1-5-dtr-TEST.yaml.zip)

**Comment by brews** [comment]
Moving this back to "draft" as we may still use tasmin files.

**Comment by brews** [comment]
I'm closing this as we're now using the tasmin parameter files.

**Pull request closed without merging**
