### PR TITLE
add parameter files for tasmax model runs

### PR DESCRIPTION
**Pull request by dgergel**
This PR adds .yaml files for running `tasmax` for the following models: AWI-CM-1-1-MR, BCC-CSM2-MR, CNRM-CM6-1, CanESM5, EC-Earth3, FOALS-g3, INM-CM5-0, KACE-1-0-G, MIROC6, NorESM2-LM.

### CODE REVIEW

**Review by brews — CHANGES_REQUESTED** [review]
Cool stuff. I got a few of these to run. Here are some comments

- [ ] The [BCC-CSM2-MR download run](https://dc6argo.westeurope.cloudapp.azure.com/workflows/argo/download-cmip6-wdq7t) is having trouble with ssp126. Looks like it can't find an entry from the catalog and errors with
```
Searching catalog
/opt/conda/lib/python3.9/site-packages/intake_esm/search.py:107: UserWarning: Query returned zero results.
  warn(message)
/opt/conda/lib/python3.9/site-packages/intake_esm/core.py:890: UserWarning: There are no datasets to load! Returning an empty dictionary.
  warn('There are no datasets to load! Returning an empty dictionary.')
Traceback (most recent call last):
  File "/argo/staging/script", line 20, in <module>
    raise ValueError("catalog does not have one entry, reconsider input IDs so only one entry")
ValueError: catalog does not have one entry, reconsider input IDs so only one entry
```
- [ ] Same goes for the [INM-CM5-0 and ssp245, ssp126 download run](https://dc6argo.westeurope.cloudapp.azure.com/workflows/argo/download-cmip6-tjhpn).
- [ ] [FGOALS-g3 ssp126 and ssp245](https://dc6argo.westeurope.cloudapp.azure.com/workflows/argo/download-cmip6-d8f49) have the same issue.
- [ ] KACE [makes it to the cleaning step but doesn't make it past cleaning](https://dc6argo.westeurope.cloudapp.azure.com/workflows/argo/clean-cmip6-hc5h7) throwing :
```
INFO:dodola.services:Starting clean_cmip6 dodola service
INFO:dodola.repository:Read az://raw/KACE-1-0-G/historical/tasmax.zarr
Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 105, in cleancmip6
    services.clean_cmip6(x, out, drop_leapdays)
  File "/opt/dodola/dodola/services.py", line 28, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 318, in clean_cmip6
    cleaned_ds = standardize_gcm(ds, leapday_removal)
  File "/opt/dodola/dodola/core.py", line 350, in standardize_gcm
    ds_noleap = xclim_remove_leapdays(ds_cleaned)
  File "/opt/dodola/dodola/core.py", line 371, in xclim_remove_leapdays
    ds_noleap = convert_calendar(ds, target="noleap")
  File "/opt/conda/lib/python3.9/site-packages/xclim/core/calendar.py", line 178, in convert_calendar
    raise ValueError(
ValueError: Argument `align_on` must be specified with either 'date' or 'year' when converting to or from a '360_day' calendar.
```

Thinking about how to handle this: As a general rule, for now, I guess I'd say we can merge a file if the run parameters is good (even if it catches an error in our workflow). Bad specs (e.g. spelling errors, or missing data in CMIP6-in-the-cloud) need to be fixed before merging. What do you think, @dgergel ?

**Comment by brews** [comment]
[CNRM also got caught in the cleaning step](https://dc6argo.westeurope.cloudapp.azure.com/workflows/argo/clean-cmip6-bdpbj). On quick look, it looks like something with chunking. We might need have some work there in the workflow and not the parameter file.

**Comment by dgergel** [comment]
Lesson learned: version numbers are _not_ the same between SSPs for the same model :-( 

I've fixed the version numbers for FGOALS-g3, INM-CM5-0, and BCC-CSM2-MR. 

Looks like the KACE-1-0-G model is on a 360-day calendar, so it needs the same fix as the Hadley center model that we were discussing. 

I can't see the CNRM error log, but sounds like you have an idea of what's going on there? 

Agreed, if it's an error in the workflow, let's merge, but if missing data, then hold off. So this is probably okay to merge once you rerun those three models _and_ if they don't err this time?

**Comment by brews** [comment]
@dgergel CNRM had this error:
```
az://clean/CNRM-CM6-1/historical/tasmax.zarr
az://scratch/clean-cmip6-bdpbj/clean-cmip6-bdpbj-2946619945/out.zarr
ds1:
<xarray.Dataset>
Dimensions:      (lat: 128, lon: 256, time: 23725, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float64 -88.93 -87.54 -86.14 -84.74 ... 86.14 87.54 88.93
  * lon          (lon) float64 0.0 1.406 2.812 4.219 ... 354.4 355.8 357.2 358.6
  * time         (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(23725, 1), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(365, 128, 256), meta=np.ndarray>
Attributes: (12/59)
    CMIP6_CV_version:        cv=6.2.3.0-7-g2019642
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   CNRM-CM6-1_historical_r1i1p1f2
    NCO:                     "4.5.5"
    activity_id:             CMIP
    arpege_minor_version:    6.3.2
    ...                      ...
    title:                   CNRM-CM6-1 model output prepared for CMIP6 / CMI...
    tracking_id:             hdl:21.14100/404d17a6-e9d7-43e7-9d93-e2ddc57979a9
    variable_id:             tasmax
    variant_label:           r1i1p1f2
    version_id:              v20180917
    xios_commit:             1442-shuffle
ds2:
<xarray.Dataset>
Dimensions:      (lat: 128, lon: 256, time: 31390, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float64 -88.93 -87.54 -86.14 -84.74 ... 86.14 87.54 88.93
  * lon          (lon) float64 0.0 1.406 2.812 4.219 ... 354.4 355.8 357.2 358.6
  * time         (time) object 2015-01-01 12:00:00 ... 2100-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(15706, 2), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(730, 128, 256), meta=np.ndarray>
Attributes: (12/57)
    CMIP6_CV_version:        cv=6.2.3.0-7-g2019642
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   CNRM-CM6-1_ssp370_r1i1p1f2
    activity_id:             ScenarioMIP AerChemMIP
    arpege_minor_version:    6.3.2
    branch_method:           standard
    ...                      ...
    title:                   CNRM-CM6-1 model output prepared for CMIP6 / Sce...
    tracking_id:             hdl:21.14100/ef7a9eea-e677-473f-9bb3-1d7881dc67ad
    variable_id:             tasmax
    variant_label:           r1i1p1f2
    version_id:              v20190219
    xios_commit:             1442-shuffle
Traceback (most recent call last):
  File "/argo/staging/script", line 19, in <module>
    ds = ds.chunk({"time": 365, "lat": -1, "lon": -1, "bnds": 2})
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2157, in chunk
    raise ValueError(
ValueError: some chunks keys are not dimensions on this object: {'bnds'}
```

On first look, it appears it has dim "axis_nbounds" instead of "bnds"...

(if I forget on Monday, remind me and I'll show you how to easily get archived logs for deleted pods off scatch storage)

**Review by brews — APPROVED** [review]
Awesome. The updated files pass through download and cleaning steps. 👍

**Pull request merged**
