### PR TITLE
add 1-deg domain file and notebook used to create it

### PR DESCRIPTION
**Pull request by dgergel**
This PR creates a 1-deg domain file and adds the notebook used to create it. It also creates a new directory for grids - the 0.25-deg grid will later be added to it.

### CODE REVIEW

**Comment by kemccusker** [comment]
Nice work, @dgergel! My only suggestion is that in the notebook, instead of testing the regridding with the in-memory `domain` dataset, you can open up the domain netcdf file that was just saved and use that in the regrid test. Sometimes whacky stuff can happen with I/O (tho I wouldn't expect it here, just better to be safe).

**Review by brews — APPROVED** [review]
Thanks for this @dgergel . I think this looks good.

What are your thoughts on saving this as a NetCDF vs Zarr store? We could stream the zarr store from Azure's blob storage. If it's NetCDF, we'd need to mount storage as a file system or manually transfer the file, adding a few steps to the process. On the other hand, NetCDF is more reliable and works with established tools.

**Comment by dgergel** [comment]
@brews if zarr is easier, I think we can definitely work with this as a zarr store. I can go ahead and save it as a zarr as well if you think that'll be easier for the pipeline.

**Comment by dgergel** [comment]
@kemccusker thanks for the review! I just updated the notebook per your suggestion.

**Comment by dgergel** [comment]
@kemccusker @brews since we had forgotten to merge this before, I added the 1/4 degree grid updates as well as the 1/4 degree domain file to this. Ready for another review.

**Review by brews — APPROVED** [review]
@dgergel Last night I got the 1x1 domain file in AZ storage to run with `dodola regrid` in v0.2.0, so this PR is good to go as far as I'm concerned. 👍

**Pull request merged**
